In [2]:
!dir

 Volume in drive D is New Volume
 Volume Serial Number is ECB8-A3DD

 Directory of d:\General_Study\PiNO_2025

03/14/2025  07:12 PM    <DIR>          .
03/13/2025  12:31 AM    <DIR>          ..
03/14/2025  06:09 PM    <DIR>          data
03/14/2025  10:33 PM    <DIR>          pino_env
03/14/2025  10:33 PM            55,240 SciGlass.ipynb
               1 File(s)         55,240 bytes
               4 Dir(s)  107,968,479,232 bytes free

In [5]:
import pyodbc
import pandas as pd

# Absolute path is safer on Windows
db_path = r"C:\Users\YourUsername\Path\to\select.mdb"

# Microsoft Access ODBC Driver
conn_str = r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + db_path

try:
    conn = pyodbc.connect(conn_str)
    cursor = conn.cursor()

    # Get table names
    cursor.execute("SELECT name FROM MSysObjects WHERE type=1 AND flags=0")
    tables = [row[0] for row in cursor.fetchall()]
    print("Tables in the database:", tables)

    if tables:
        # Read first table into a DataFrame
        df = pd.read_sql(f"SELECT * FROM [{tables[0]}]", conn)
        print(df.head())

    conn.close()
except Exception as e:
    print("Error:", e)

Error: ('HY024', "[HY024] [Microsoft][ODBC Microsoft Access Driver] '(unknown)' is not a valid path. Make sure that the path name is spelled correctly and that you are connected to the server on which the file resides. (-1023) (SQLDriverConnect); [HY024] [Microsoft][ODBC Microsoft Access Driver] '(unknown)' is not a valid path. Make sure that the path name is spelled correctly and that you are connected to the server on which the file resides. (-1023)")

In [6]:
import pandas_access as mdb


db_path = r"./data/SciGlass/select/select.mdb"

# Read tables
df_dict = mdb.read_schema(db_path)

# Display table names
print("Tables:", df_dict.keys())

# Read a specific table into a DataFrame
df = mdb.read_table(db_path, list(df_dict.keys())[0])

FileNotFoundError: [WinError 2] The system cannot find the file specified

In [9]:
from meza import io

records = io.read(db_path) # only file path, no file objects
print(next(records))

You must install [mdbtools](http://sourceforge.net/projects/mdbtools/) in order to use this function

None

In [11]:
import pyodbc
import pandas as pd

# Update this to the full path of your .mdb file
db_path = r"./data/SciGlass/select/select.mdb"

# ODBC connection string
# conn_str = rf"DRIVER={{Microsoft Access Driver (*.mdb, *.accdb)}};DBQ={db_path}"
conn_str = rf"DRIVER={{Microsoft Access Driver (*.mdb)}};DBQ={db_path}"


try:
    # Connect to the database
    conn = pyodbc.connect(conn_str)
    cursor = conn.cursor()

    # Get all table names
    cursor.execute("SELECT name FROM MSysObjects WHERE type=1 AND flags=0")
    tables = [row[0] for row in cursor.fetchall()]
    print("Tables in the database:", tables)

    # Read first table into DataFrame
    if tables:
        table_name = tables[0]  # Change this if needed
        df = pd.read_sql(f"SELECT * FROM [{table_name}]", conn)

        # Display the first few rows
        print(df.head())

    # Close the connection
    conn.close()

except Exception as e:
    print("Error:", e)

Error: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')

In [ ]:
from glasspy.data.load import SciGlass


sciglass = SciGlass()
data = sciglass.data
print(data.head())

[GlassPy] Initial installation or an update was detected.
[GlassPy] Downloading necessary files to your computer...
[GlassPy] This is only required once and may take a few minutes.
[GlassPy] Download completed!
            elements                                                         \
                   H   Li   Be    B    C    N         O    F        Na   Mg
ID
20400020000      0.0  0.0  0.0  0.0  0.0  0.0  0.666667  0.0  0.000000  0.0
20500020001      0.0  0.0  0.0  0.0  0.0  0.0  0.579213  0.0  0.196815  0.0
20500020002      0.0  0.0  0.0  0.0  0.0  0.0  0.580869  0.0  0.193449  0.0
20500020003      0.0  0.0  0.0  0.0  0.0  0.0  0.581986  0.0  0.187167  0.0
20500020004      0.0  0.0  0.0  0.0  0.0  0.0  0.583672  0.0  0.183080  0.0

             ...              property                      \
             ... SurfaceTensionAboveTg SurfaceTension1173K
ID           ...
20400020000  ...                   NaN                 NaN
20500020001  ...                   NaN                 NaN
20500020002  ...                   NaN                 NaN
20500020003  ...                   NaN                 NaN
20500020004  ...                   NaN                 NaN

                                                                         \
            SurfaceTension1473K SurfaceTension1573K SurfaceTension1673K
ID
20400020000                 NaN                 NaN                 NaN
20500020001                 NaN                 NaN                 NaN
20500020002                 NaN                 NaN                 NaN
20500020003                 NaN                 NaN                 NaN
20500020004                 NaN                 NaN                 NaN

                    metadata                                        \
            ChemicalAnalysis           Author  Year NumberElements
ID
20400020000            False  Volarovich M.P.  1936              2
20500020001            False         Hoj J.W.  1992              5
20500020002            False         Hoj J.W.  1992              5
20500020003            False         Hoj J.W.  1992              5
20500020004            False         Hoj J.W.  1992              5


            NumberCompounds
ID
20400020000               1
20500020001               4
20500020002               4
20500020003               4
20500020004               4

[5 rows x 793 columns]

In [14]:
data.shape

(283102, 793)

In [69]:
memory_usage = compounds_data.memory_usage(deep=True).sum()
print(f"Memory usage of compounds_data DataFrame: {memory_usage / (1024 ** 2):.2f} MB")

Memory usage of compounds_data DataFrame: 1352.10 MB

In [15]:
data.head()

            elements                                                         \
                   H   Li   Be    B    C    N         O    F        Na   Mg
ID
20400020000      0.0  0.0  0.0  0.0  0.0  0.0  0.666667  0.0  0.000000  0.0
20500020001      0.0  0.0  0.0  0.0  0.0  0.0  0.579213  0.0  0.196815  0.0
20500020002      0.0  0.0  0.0  0.0  0.0  0.0  0.580869  0.0  0.193449  0.0
20500020003      0.0  0.0  0.0  0.0  0.0  0.0  0.581986  0.0  0.187167  0.0
20500020004      0.0  0.0  0.0  0.0  0.0  0.0  0.583672  0.0  0.183080  0.0

             ...              property                      \
             ... SurfaceTensionAboveTg SurfaceTension1173K
ID           ...
20400020000  ...                   NaN                 NaN
20500020001  ...                   NaN                 NaN
20500020002  ...                   NaN                 NaN
20500020003  ...                   NaN                 NaN
20500020004  ...                   NaN                 NaN

                                                                         \
            SurfaceTension1473K SurfaceTension1573K SurfaceTension1673K
ID
20400020000                 NaN                 NaN                 NaN
20500020001                 NaN                 NaN                 NaN
20500020002                 NaN                 NaN                 NaN
20500020003                 NaN                 NaN                 NaN
20500020004                 NaN                 NaN                 NaN

                    metadata                                        \
            ChemicalAnalysis           Author  Year NumberElements
ID
20400020000            False  Volarovich M.P.  1936              2
20500020001            False         Hoj J.W.  1992              5
20500020002            False         Hoj J.W.  1992              5
20500020003            False         Hoj J.W.  1992              5
20500020004            False         Hoj J.W.  1992              5


            NumberCompounds
ID
20400020000               1
20500020001               4
20500020002               4
20500020003               4
20500020004               4

[5 rows x 793 columns]

In [17]:
list(data.columns)

[('elements', 'H'),
 ('elements', 'Li'),
 ('elements', 'Be'),
 ('elements', 'B'),
 ('elements', 'C'),
 ('elements', 'N'),
 ('elements', 'O'),
 ('elements', 'F'),
 ('elements', 'Na'),
 ('elements', 'Mg'),
 ('elements', 'Al'),
 ('elements', 'Si'),
 ('elements', 'P'),
 ('elements', 'S'),
 ('elements', 'Cl'),
 ('elements', 'K'),
 ('elements', 'Ca'),
 ('elements', 'Sc'),
 ('elements', 'Ti'),
 ('elements', 'V'),
 ('elements', 'Cr'),
 ('elements', 'Mn'),
 ('elements', 'Fe'),
 ('elements', 'Co'),
 ('elements', 'Ni'),
 ('elements', 'Cu'),
 ('elements', 'Zn'),
 ('elements', 'Ga'),
 ('elements', 'Ge'),
 ('elements', 'As'),
 ('elements', 'Se'),
 ('elements', 'Br'),
 ('elements', 'Rb'),
 ('elements', 'Sr'),
 ('elements', 'Y'),
 ('elements', 'Zr'),
 ('elements', 'Nb'),
 ('elements', 'Mo'),
 ('elements', 'Ru'),
 ('elements', 'Rh'),
 ('elements', 'Pd'),
 ('elements', 'Ag'),
 ('elements', 'Cd'),
 ('elements', 'In'),
 ('elements', 'Sn'),
 ('elements', 'Sb'),
 ('elements', 'Te'),
 ('elements', 'I'),
 ('elements', 'Cs'),
 ('elements', 'Ba'),
 ('elements', 'La'),
 ('elements', 'Ce'),
 ('elements', 'Pr'),
 ('elements', 'Nd'),
 ('elements', 'Sm'),
 ('elements', 'Eu'),
 ('elements', 'Gd'),
 ('elements', 'Tb'),
 ('elements', 'Dy'),
 ('elements', 'Ho'),
 ('elements', 'Er'),
 ('elements', 'Tm'),
 ('elements', 'Yb'),
 ('elements', 'Lu'),
 ('elements', 'Hf'),
 ('elements', 'Ta'),
 ('elements', 'W'),
 ('elements', 'Re'),
 ('elements', 'Pt'),
 ('elements', 'Au'),
 ('elements', 'Hg'),
 ('elements', 'Tl'),
 ('elements', 'Pb'),
 ('elements', 'Bi'),
 ('elements', 'Th'),
 ('elements', 'U'),
 ('compounds', 'SiO2'),
 ('compounds', 'P2O5'),
 ('compounds', 'ZrO2'),
 ('compounds', 'Na2O'),
 ('compounds', 'Al2O3'),
 ('compounds', 'Fe2O3'),
 ('compounds', 'CaO'),
 ('compounds', 'MgO'),
 ('compounds', 'K2O'),
 ('compounds', 'MnO'),
 ('compounds', 'GeO2'),
 ('compounds', 'Li2O'),
 ('compounds', 'Ta2O5'),
 ('compounds', 'ZnO'),
 ('compounds', 'SrO'),
 ('compounds', 'CdO'),
 ('compounds', 'SnO2'),
 ('compounds', 'B2O3'),
 ('compounds', 'La2O3'),
 ('compounds', 'Ga2O3'),
 ('compounds', 'Y2O3'),
 ('compounds', 'TiO2'),
 ('compounds', 'Nb2O5'),
 ('compounds', 'PbO'),
 ('compounds', 'HfO2'),
 ('compounds', 'WO3'),
 ('compounds', 'Sb2O3'),
 ('compounds', 'Bi2O3'),
 ('compounds', 'CdCl2'),
 ('compounds', 'KCl'),
 ('compounds', 'BaCl2'),
 ('compounds', 'CsCl'),
 ('compounds', 'TlCl'),
 ('compounds', 'CaCl2'),
 ('compounds', 'CdI2'),
 ('compounds', 'CsI'),
 ('compounds', 'BaI2'),
 ('compounds', 'PbI2'),
 ('compounds', 'CdBr2'),
 ('compounds', 'KBr'),
 ('compounds', 'CsBr'),
 ('compounds', 'BaBr2'),
 ('compounds', 'CdF2'),
 ('compounds', 'NaCl'),
 ('compounds', 'BaF2'),
 ('compounds', 'PbF2'),
 ('compounds', 'PbCl2'),
 ('compounds', 'NaF'),
 ('compounds', 'InF3'),
 ('compounds', 'GaF3'),
 ('compounds', 'ZnF2'),
 ('compounds', 'LaF3'),
 ('compounds', 'YF3'),
 ('compounds', 'BaO'),
 ('compounds', 'Cr2O3'),
 ('compounds', 'AlF3'),
 ('compounds', 'SiF4'),
 ('compounds', 'Cu2O'),
 ('compounds', 'CaF2'),
 ('compounds', 'BeO'),
 ('compounds', 'CuO'),
 ('compounds', 'Nd2O3'),
 ('compounds', 'CeO2'),
 ('compounds', 'Cs2O'),
 ('compounds', 'As2O3'),
 ('compounds', 'SO3'),
 ('compounds', 'F'),
 ('compounds', 'NH4NO3'),
 ('compounds', 'MgF2'),
 ('compounds', 'SrF2'),
 ('compounds', 'Rb2O'),
 ('compounds', 'Pd'),
 ('compounds', 'Rh'),
 ('compounds', 'Ru'),
 ('compounds', 'MoO3'),
 ('compounds', 'FeO'),
 ('compounds', 'PbBr2'),
 ('compounds', 'Mn2O3'),
 ('compounds', 'KF'),
 ('compounds', 'SO2'),
 ('compounds', 'ThO2'),
 ('compounds', 'Ag2O'),
 ('compounds', 'Ag2S'),
 ('compounds', 'Fe'),
 ('compounds', 'Mo'),
 ('compounds', 'TeO2'),
 ('compounds', 'Tl2O'),
 ('compounds', 'CoO'),
 ('compounds', 'In2O3'),
 ('compounds', 'Sc2O3'),
 ('compounds', 'ZrF4'),
 ('compounds', 'ThF4'),
 ('compounds', 'HfF4'),
 ('compounds', 'F2'),
 ('compounds', 'NiO'),
 ('compounds', 'ErF3'),
 ('compounds', 'V2O5'),
 ('compounds', 'Li2SO4'),
 ('compounds', 'As2O5'),
 ('compounds', 'Cl'),
 ('compounds', 'MnO2'),
 ('compounds', 'OH'),
 ('compounds', 'Sm2O3'),
 ('compounds', 'Gd2O3'),
 ('compounds', 'Tb2O3'),
 ('compounds', 'Dy2O3'),
 ('compounds', 'Ho2O3'),
 ('compounds', 'Er2O3'),
 ('compounds', 'Yb2O3'),
 ('compounds', 'LiF'),
 ('compounds', 'BF3'),
 ('compounds', 'AlN'),
 ('compounds', 'Co3O4'),
 ('compounds', 'Fe3O4'),
 ('compounds', 'ZnCl2'),
 ('compounds', 'H2O'),
 ('compounds', 'SnO'),
 ('compounds', 'Mn3O4'),
 ('compounds', 'Ce2O3'),
 ('compounds', 'Pr2O3'),
 ('compounds', 'CrO3'),
 ('compounds', 'KHF2'),
 ('compounds', 'ScF3'),
 ('compounds', 'BiF3'),
 ('compounds', 'S'),
 ('compounds', 'FeS2'),
 ('compounds', 'VO6'),
 ('compounds', 'LiCl'),
 ('compounds', 'Si2N4'),
 ('compounds', 'TeO3'),
 ('compounds', 'AgI'),
 ('compounds', 'UO2'),
 ('compounds', 'NaBr'),
 ('compounds', 'NaI'),
 ('compounds', 'Br'),
 ('compounds', 'CsF'),
 ('compounds', 'NdF3'),
 ('compounds', 'MnF2'),
 ('compounds', 'RbF'),
 ('compounds', 'SnF2'),
 ('compounds', 'I'),
 ('compounds', 'Na2SO4'),
 ('compounds', 'Sb2O5'),
 ('compounds', 'TeCl4'),
 ('compounds', 'WCl6'),
 ('compounds', 'Pr6O11'),
 ('compounds', 'VO2'),
 ('compounds', 'GdF3'),
 ('compounds', 'PrF3'),
 ('compounds', 'Co2O3'),
 ('compounds', 'Ti2O3'),
 ('compounds', 'UO3'),
 ('compounds', 'Ag'),
 ('compounds', 'CuI'),
 ('compounds', 'CuCl'),
 ('compounds', 'SiC'),
 ('compounds', 'Si3N4'),
 ('compounds', 'Na2S'),
 ('compounds', '(NH4)2SO4'),
 ('compounds', 'K2SO4'),
 ('compounds', 'Cs2SO4'),
 ('compounds', 'EuF3'),
 ('compounds', 'Na3AlF6'),
 ('compounds', 'CaS'),
 ('compounds', 'Eu2O3'),
 ('compounds', 'Se'),
 ('compounds', 'CdS'),
 ('compounds', 'Mo2O3'),
 ('compounds', 'FeCl2'),
 ('compounds', 'Ni2O3'),
 ('compounds', 'Al'),
 ('compounds', 'BN'),
 ('compounds', 'MoO'),
 ('compounds', 'PrO2'),
 ('compounds', 'TbO2'),
 ('compounds', 'V2O3'),
 ('compounds', 'MnBr2'),
 ('compounds', 'MnCl2'),
 ('compounds', 'CrF3'),
 ('compounds', 'NO2'),
 ('compounds', 'NH4Cl'),
 ('compounds', 'SeO2'),
 ('compounds', 'Lu2O3'),
 ('compounds', 'CeF3'),
 ('compounds', 'TbF3'),
 ('compounds', 'HoF3'),
 ('compounds', 'YbF3'),
 ('compounds', 'LuF3'),
 ('compounds', 'SmF3'),
 ('compounds', 'DyF3'),
 ('compounds', 'TmF3'),
 ('compounds', 'CuBr'),
 ('compounds', 'LiBr'),
 ('compounds', 'CaBr2'),
 ('compounds', 'CaI2'),
 ('compounds', 'LiI'),
 ('compounds', 'KI'),
 ('compounds', 'GeO'),
 ('compounds', 'N2O5'),
 ('compounds', 'NdCl3'),
 ('compounds', 'BiCl3'),
 ('compounds', 'BeF2'),
 ('compounds', 'PbF3'),
 ('compounds', 'SbO2'),
 ('compounds', 'BiOCl'),
 ('compounds', 'ZnSO4'),
 ('compounds', 'U3O8'),
 ('compounds', 'Mn2O7'),
 ('compounds', 'HgO'),
 ('compounds', 'Tm2O3'),
 ('compounds', 'PbSO4'),
 ('compounds', 'SrCl2'),
 ('compounds', 'SrBr2'),
 ('compounds', 'BaSO4'),
 ('compounds', 'LaCl3'),
 ('compounds', 'LaBr3'),
 ('compounds', 'La2(SO4)3'),
 ('compounds', 'BiOBr'),
 ('compounds', 'ZnBr2'),
 ('compounds', 'RbCl'),
 ('compounds', 'RbBr'),
 ('compounds', 'Rb2SO4'),
 ('compounds', 'BeSO4'),
 ('compounds', 'MgCl2'),
 ('compounds', 'MgBr2'),
 ('compounds', 'MgSO4'),
 ('compounds', 'AgCl'),
 ('compounds', 'AgBr'),
 ('compounds', 'SnCl2'),
 ('compounds', 'Nb2O3'),
 ('compounds', 'HgI2'),
 ('compounds', 'HgBr2'),
 ('compounds', 'HgCl2'),
 ('compounds', 'TlI'),
 ('compounds', 'FeF3'),
 ('compounds', 'CuF2'),
 ('compounds', 'UF4'),
 ('compounds', 'CoF2'),
 ('compounds', 'PbO2'),
 ('compounds', 'Tl2O3'),
 ('compounds', 'Pb3O4'),
 ('compounds', 'SbF3'),
 ('compounds', 'TiF4'),
 ('compounds', 'PF5'),
 ('compounds', 'NbF5'),
 ('compounds', 'VF3'),
 ('compounds', 'FeF2'),
 ('compounds', 'NiF2'),
 ('compounds', 'AgF'),
 ('compounds', 'SiO'),
 ('compounds', 'Sn2O3'),
 ('compounds', 'TlF'),
 ('compounds', 'KHSO4'),
 ('compounds', 'Si'),
 ('compounds', 'ZnI2'),
 ('compounds', 'Ba3N2'),
 ('compounds', 'SbCl3'),
 ('compounds', 'Li2SO3'),
 ('compounds', 'TlBr'),
 ('compounds', 'ThCl4'),
 ('compounds', 'HgF'),
 ('compounds', 'P3N5'),
 ('compounds', 'PF6'),
 ('compounds', 'Zn'),
 ('compounds', 'C'),
 ('compounds', 'Ta2O3'),
 ('compounds', 'RuO2'),
 ('compounds', 'PF3'),
 ('compounds', 'TaF5'),
 ('compounds', 'HgS'),
 ('compounds', 'Na'),
 ('compounds', 'P'),
 ('compounds', 'O'),
 ('compounds', 'N'),
 ('compounds', 'RbI'),
 ('compounds', 'Tb4O7'),
 ('compounds', 'NbO2F'),
 ('compounds', 'Li2S'),
 ('compounds', 'Tb3O7'),
 ('compounds', 'P2S5'),
 ('compounds', 'As2S3'),
 ('compounds', 'SiS2'),
 ('compounds', 'CO2'),
 ('compounds', 'Cu'),
 ('compounds', 'VCl3'),
 ('compounds', 'SeO3'),
 ('compounds', 'Ag2SO4'),
 ('compounds', 'ZnS'),
 ('compounds', 'B2S3'),
 ('compounds', 'C2H5OH'),
 ('compounds', 'NH4F'),
 ('compounds', 'FeS'),
 ('compounds', 'Li2CO3'),
 ('compounds', 'Na2CO3'),
 ('compounds', 'SnF4'),
 ('compounds', 'Sn'),
 ('compounds', 'Al2(SO4)3'),
 ('compounds', 'Pt'),
 ('compounds', 'Cr3O4'),
 ('compounds', 'Ti3B4'),
 ('compounds', 'Ca3N2'),
 ('compounds', 'PdO'),
 ('compounds', 'EuF2'),
 ('compounds', 'FeBr2'),
 ('compounds', 'CoBr2'),
 ('compounds', 'MoO2'),
 ('compounds', 'Rh2O3'),
 ('compounds', 'AsF5'),
 ('compounds', 'CuCl2'),
 ('compounds', 'AlCl3'),
 ('compounds', 'Pr'),
 ('compounds', 'As2Se3'),
 ('compounds', 'Sb2S3'),
 ('compounds', 'K2S'),
 ('compounds', 'TiO'),
 ('compounds', 'RhO2'),
 ('compounds', 'PCl5'),
 ('compounds', 'PON'),
 ('compounds', 'GaBr3'),
 ('compounds', 'CeF4'),
 ('compounds', 'Ga2S3'),
 ('compounds', 'La2S3'),
 ('compounds', 'TiF3'),
 ('compounds', 'Ni'),
 ('compounds', 'Pb'),
 ('compounds', 'Cu2S'),
 ('compounds', 'Sb'),
 ('compounds', 'CuSO4'),
 ('compounds', 'VOSO4'),
 ('compounds', 'Y2(SO4)3'),
 ('compounds', 'SbO'),
 ('compounds', 'LiNO3'),
 ('compounds', 'GeS2'),
 ('compounds', 'GeS'),
 ('compounds', 'In2S3'),
 ('compounds', 'Bi'),
 ('compounds', 'Te'),
 ('compounds', 'PbS'),
 ('compounds', 'As2Te3'),
 ('compounds', 'As'),
 ('compounds', 'Ge'),
 ('compounds', 'Li3N'),
 ('compounds', 'Na3N'),
 ('compounds', 'K3N'),
 ('compounds', 'NH4H2PO4'),
 ('compounds', 'NH4PF6'),
 ('compounds', '(NH4)3PO4'),
 ('compounds', 'NH4HF2'),
 ('compounds', 'ErCl3'),
 ('compounds', 'VF5'),
 ('compounds', 'MoF5'),
 ('compounds', 'PrCl3'),
 ('compounds', 'CoSO4'),
 ('compounds', 'Na2HPO4'),
 ('compounds', 'Pr2(SO4)3'),
 ('compounds', 'CaSO4'),
 ('compounds', 'EuCl3'),
 ('compounds', 'TeF4'),
 ('compounds', 'Ga'),
 ('compounds', 'In'),
 ('compounds', 'Ca'),
 ('compounds', 'N2'),
 ('compounds', 'SrSO4'),
 ('compounds', 'CdSO4'),
 ('compounds', 'Pr2S3'),
 ('compounds', 'Gd2S3'),
 ('compounds', 'Tl'),
 ('compounds', 'Cd'),
 ('compounds', 'GeSe2'),
 ('compounds', 'Sb2Se3'),
 ('compounds', 'Ag2Se'),
 ('compounds', 'ZnSe'),
 ('compounds', 'B'),
 ('compounds', 'Tl2Se'),
 ('compounds', 'GeSe'),
 ('compounds', 'PbSe'),
 ('compounds', 'AsSe'),
 ('compounds', 'Er2S3'),
 ('compounds', 'AsI3'),
 ('compounds', 'Sb2Te3'),
 ('compounds', 'GeTe4'),
 ('compounds', 'Tl2S'),
 ('compounds', 'Mn'),
 ('compounds', 'GeTe'),
 ('compounds', 'Bi2S3'),
 ('compounds', 'Nd2S3'),
 ('compounds', 'EuS'),
 ('compounds', 'BaS'),
 ('compounds', 'Tl2Te'),
 ('compounds', 'SrS'),
 ('compounds', 'CdTe'),
 ('compounds', 'Ce2S3'),
 ('compounds', 'Sm2S3'),
 ('compounds', 'Tb2S3'),
 ('compounds', 'Dy2S3'),
 ('compounds', 'Ho2S3'),
 ('compounds', 'Y2S3'),
 ('compounds', 'MnS'),
 ('compounds', 'La'),
 ('compounds', 'Ce'),
 ('compounds', 'GeSe3'),
 ('compounds', 'Cu2Se'),
 ('compounds', 'Cu2Te'),
 ('compounds', 'Be'),
 ('compounds', 'Mg'),
 ('compounds', 'Hg'),
 ('compounds', 'AsBr3'),
 ('compounds', 'Pr2Se3'),
 ('compounds', 'Y'),
 ('compounds', 'Li2Se'),
 ('compounds', 'GeBr4'),
 ('compounds', 'SbSI'),
 ('compounds', 'Cs'),
 ('compounds', 'SnS'),
 ('compounds', 'SnS2'),
 ('compounds', 'CuS'),
 ('compounds', 'BiI3'),
 ('compounds', 'Ti2S3'),
 ('compounds', 'TiS2'),
 ('compounds', 'TaS2'),
 ('compounds', 'Ge2S3'),
 ('compounds', 'Ge2Se3'),
 ('compounds', 'SnI2'),
 ('compounds', 'GeSe4'),
 ('compounds', 'GeS3'),
 ('compounds', 'AsS2'),
 ('compounds', 'In2Se3'),
 ('compounds', 'Bi2Se3'),
 ('compounds', 'B2Se3'),
 ('compounds', 'P4Se3'),
 ('compounds', 'P4Se4'),
 ('compounds', 'GeI4'),
 ('compounds', 'Ag2Te'),
 ('compounds', 'Tl2Te3'),
 ('compounds', 'PbTe'),
 ('compounds', 'SnSe2'),
 ('compounds', 'SnSe'),
 ('compounds', 'K'),
 ('compounds', 'Rb'),
 ('compounds', 'Tl2Se3'),
 ('compounds', 'SnTe'),
 ('compounds', 'Ba'),
 ('compounds', 'HgSe'),
 ('compounds', 'BiTe'),
 ('compounds', 'InTe'),
 ('compounds', 'GaTe'),
 ('compounds', 'Tb'),
 ('compounds', 'Nd'),
 ('compounds', 'Dy'),
 ('compounds', 'Ag2CO3'),
 ('compounds', 'AgNO3'),
 ('compounds', 'BaSe'),
 ('compounds', 'Ga2Se3'),
 ('compounds', 'SrSe'),
 ('compounds', 'Er'),
 ('compounds', 'Yb'),
 ('compounds', 'Bi2Te3'),
 ('compounds', 'CdSe'),
 ('compounds', 'AsS'),
 ('compounds', 'SbI3'),
 ('compounds', 'Gd'),
 ('compounds', 'Sc'),
 ('compounds', 'H2S'),
 ('compounds', 'Al2S3'),
 ('compounds', 'Na2Se'),
 ('compounds', 'Lu'),
 ('compounds', 'Eu'),
 ('compounds', 'NiTe'),
 ('compounds', 'NiCl2'),
 ('compounds', 'NiI2'),
 ('compounds', 'Tm2S3'),
 ('compounds', 'TlSe'),
 ('compounds', 'SbS2'),
 ('compounds', 'ErO2'),
 ('compounds', 'YbO2'),
 ('compounds', 'GaSe'),
 ('compounds', 'Zr'),
 ('compounds', 'Tm'),
 ('compounds', 'K2CO3'),
 ('compounds', 'MgCO3'),
 ('compounds', 'Sr'),
 ('compounds', 'Nb'),
 ('compounds', 'W'),
 ('compounds', 'Ta'),
 ('compounds', 'TlS2'),
 ('compounds', 'Tl2TiS3'),
 ('compounds', 'P2Se3'),
 ('compounds', 'Li'),
 ('compounds', 'InSe'),
 ('compounds', 'SiSe2'),
 ('compounds', 'Sm'),
 ('compounds', 'Ho'),
 ('compounds', 'Ca(NO3)2'),
 ('compounds', 'KNO3'),
 ('compounds', 'Cd(NO3)2'),
 ('compounds', 'Ag4SSe'),
 ('compounds', 'NiBr2'),
 ('compounds', 'AsTe'),
 ('compounds', 'Co'),
 ('compounds', 'CoCl2'),
 ('compounds', 'HgTe'),
 ('compounds', 'Ge2Se2Te'),
 ('compounds', 'Ti'),
 ('compounds', 'SO4'),
 ('compounds', 'C6H12O6'),
 ('compounds', 'FeCl3'),
 ('compounds', 'Yb2S3'),
 ('compounds', 'Au'),
 ('compounds', 'TlAsSe2'),
 ('compounds', 'Th(SO4)2'),
 ('compounds', 'ZrS2'),
 ('compounds', 'YbSe'),
 ('compounds', 'Ag2Se5'),
 ('compounds', 'CeSe'),
 ('compounds', 'HoCl3'),
 ('compounds', 'Rb2S'),
 ('compounds', 'Er2(SO4)3'),
 ('compounds', 'MgI2'),
 ('compounds', 'TlTe'),
 ('compounds', 'CdAs2'),
 ('compounds', 'GeSBr2'),
 ('compounds', 'GeSeBr2'),
 ('compounds', 'K2SiF6'),
 ('compounds', 'Sn2S3'),
 ('compounds', 'TlAsS2'),
 ('compounds', 'TlAsTe2'),
 ('compounds', 'AsSI'),
 ('compounds', 'PtCl2'),
 ('compounds', 'Bi2O5'),
 ('compounds', 'Cr'),
 ('compounds', 'V'),
 ('compounds', 'Dy2Se3'),
 ('compounds', 'Al2N3'),
 ('compounds', 'As2Te'),
 ('compounds', 'ErI3'),
 ('compounds', 'P4S3'),
 ('compounds', 'P4S7'),
 ('compounds', 'P4Se10'),
 ('compounds', 'P2Se5'),
 ('compounds', 'H3BO3'),
 ('compounds', 'GeI2'),
 ('compounds', 'U'),
 ('compounds', 'Th'),
 ('compounds', 'EuO'),
 ('compounds', 'BS2'),
 ('compounds', 'Mg3N2'),
 ('compounds', 'VN'),
 ('compounds', 'As2Se5'),
 ('compounds', 'As2Te5'),
 ('compounds', 'Cs2S'),
 ('compounds', 'GeTe2'),
 ('compounds', 'Pu2O3'),
 ('compounds', 'La2Se3'),
 ('compounds', 'AsSeI'),
 ('compounds', 'RbV2O5'),
 ('compounds', 'AsSBr'),
 ('compounds', 'GeF4'),
 ('compounds', 'GeSb2'),
 ('compounds', 'H'),
 ('compounds', 'InI3'),
 ('compounds', 'GeAs'),
 ('compounds', 'CeO'),
 ('compounds', 'ZnTe'),
 ('compounds', 'KBF4'),
 ('compounds', 'AuCl3'),
 ('compounds', 'TlS'),
 ('compounds', 'BOF'),
 ('compounds', 'NaBH4'),
 ('compounds', 'CrO'),
 ('compounds', 'P2S3'),
 ('compounds', 'Nd2(SO4)3'),
 ('compounds', 'Gd2(SO4)3'),
 ('compounds', 'DyCl3'),
 ('compounds', 'BiBr3'),
 ('compounds', 'BaO2'),
 ('compounds', 'GaS2'),
 ('compounds', 'CeCl3'),
 ('compounds', 'SmCl3'),
 ('compounds', 'GdCl3'),
 ('compounds', 'TbCl3'),
 ('compounds', 'TmCl3'),
 ('compounds', 'SeS2'),
 ('compounds', 'UO2F2'),
 ('compounds', 'ZrSe2'),
 ('compounds', 'CsHSO4'),
 ('compounds', 'NaHSO4'),
 ('compounds', 'In2Te6'),
 ('compounds', 'Ga2Te3'),
 ('compounds', 'NaPO3'),
 ('compounds', 'AgPO3'),
 ('compounds', 'MnNbOF5'),
 ('compounds', 'Cu2MoO4'),
 ('compounds', 'Cu3PO4'),
 ('compounds', 'Al(PO3)3'),
 ('compounds', 'Cl2'),
 ('compounds', 'RbNO3'),
 ('compounds', 'Ho2Se3'),
 ('compounds', 'HoAs'),
 ('compounds', 'HoSe'),
 ('compounds', 'Au2O3'),
 ('compounds', 'CuNbOF5'),
 ('compounds', 'SiCl4'),
 ('compounds', 'MnSe'),
 ('compounds', 'ReO3'),
 ('compounds', 'GaSe2'),
 ('compounds', 'Sb2Te2'),
 ('compounds', 'Sb2Te4'),
 ('compounds', 'EuCl2'),
 ('compounds', 'YbCl3'),
 ('compounds', 'GeTe4.3'),
 ('compounds', 'GaTe3'),
 ('compounds', 'ZrSiO4'),
 ('compounds', 'Ba(PO3)2'),
 ('compounds', 'AsSe2'),
 ('compounds', 'As2S5'),
 ('compounds', 'UF2'),
 ('compounds', 'Ba(H2PO4)2'),
 ('compounds', 'AlPO4'),
 ('compounds', 'AgGaS2'),
 ('compounds', 'AgAsS2'),
 ('compounds', 'MgS'),
 ('compounds', 'Na2B4O7'),
 ('compounds', 'CaCO3'),
 ('compounds', 'AsTe3'),
 ('compounds', 'Re2O7'),
 ('property', 'T0'),
 ('property', 'T1'),
 ('property', 'T2'),
 ('property', 'T3'),
 ('property', 'T4'),
 ('property', 'T5'),
 ('property', 'T6'),
 ('property', 'T7'),
 ('property', 'T8'),
 ('property', 'T9'),
 ('property', 'T10'),
 ('property', 'T11'),
 ('property', 'T12'),
 ('property', 'Viscosity773K'),
 ('property', 'Viscosity873K'),
 ('property', 'Viscosity973K'),
 ('property', 'Viscosity1073K'),
 ('property', 'Viscosity1173K'),
 ('property', 'Viscosity1273K'),
 ('property', 'Viscosity1373K'),
 ('property', 'Viscosity1473K'),
 ('property', 'Viscosity1573K'),
 ('property', 'Viscosity1673K'),
 ('property', 'Viscosity1773K'),
 ('property', 'Viscosity1873K'),
 ('property', 'Viscosity2073K'),
 ('property', 'Viscosity2273K'),
 ('property', 'Viscosity2473K'),
 ('property', 'Tg'),
 ('property', 'Tmelt'),
 ('property', 'Tliquidus'),
 ('property', 'TLittletons'),
 ('property', 'TAnnealing'),
 ('property', 'Tstrain'),
 ('property', 'Tsoft'),
 ('property', 'TdilatometricSoftening'),
 ('property', 'AbbeNum'),
 ('property', 'RefractiveIndex'),
 ('property', 'RefractiveIndexLow'),
 ('property', 'RefractiveIndexHigh'),
 ('property', 'MeanDispersion'),
 ('property', 'Permittivity'),
 ('property', 'TangentOfLossAngle'),
 ('property', 'TresistivityIs1MOhm.m'),
 ('property', 'Resistivity293K'),
 ('property', 'Resistivity373K'),
 ('property', 'Resistivity423K'),
 ('property', 'Resistivity573K'),
 ('property', 'Resistivity1073K'),
 ('property', 'Resistivity1273K'),
 ('property', 'Resistivity1473K'),
 ('property', 'Resistivity1673K'),
 ('property', 'YoungModulus'),
 ('property', 'ShearModulus'),
 ('property', 'Microhardness'),
 ('property', 'PoissonRatio'),
 ('property', 'Density293K'),
 ('property', 'Density1073K'),
 ('property', 'Density1273K'),
 ('property', 'Density1473K'),
 ('property', 'Density1673K'),
 ('property', 'ThermalConductivity'),
 ('property', 'ThermalShockRes'),
 ('property', 'CTEbelowTg'),
 ('property', 'CTE328K'),
 ('property', 'CTE373K'),
 ('property', 'CTE433K'),
 ('property', 'CTE483K'),
 ('property', 'CTE623K'),
 ('property', 'Cp293K'),
 ('property', 'Cp473K'),
 ('property', 'Cp673K'),
 ('property', 'Cp1073K'),
 ('property', 'Cp1273K'),
 ('property', 'Cp1473K'),
 ('property', 'Cp1673K'),
 ('property', 'NucleationTemperature'),
 ('property', 'NucleationRate'),
 ('property', 'TMaxGrowthVelocity'),
 ('property', 'MaxGrowthVelocity'),
 ('property', 'CrystallizationPeak'),
 ('property', 'CrystallizationOnset'),
 ('property', 'SurfaceTensionAboveTg'),
 ('property', 'SurfaceTension1173K'),
 ('property', 'SurfaceTension1473K'),
 ('property', 'SurfaceTension1573K'),
 ('property', 'SurfaceTension1673K'),
 ('metadata', 'ChemicalAnalysis'),
 ('metadata', 'Author'),
 ('metadata', 'Year'),
 ('metadata', 'NumberElements'),
 ('metadata', 'NumberCompounds')]

In [19]:
tg_col = ("property", "Tg")
smiles_col_candidates = [
    col for col in data.columns if "SMILES" in col or "compounds" in col
]

# Extracting Tg
tg_data = data[tg_col]
tg_data

ID
20400020000          NaN
20500020001      1017.15
20500020002      1096.15
20500020003      1013.15
20500020004      1013.15
                  ...
4493300611694        NaN
4493300611695        NaN
4493300611696        NaN
4493300611697        NaN
4493300611698        NaN
Name: (property, Tg), Length: 283102, dtype: float64

In [47]:
tg_data_df = pd.DataFrame(tg_data).reset_index()
tg_data_df.columns = ['ID', 'Tg']
tg_data_df

                   ID       Tg
0         20400020000      NaN
1         20500020001  1017.15
2         20500020002  1096.15
3         20500020003  1013.15
4         20500020004  1013.15
...               ...      ...
283097  4493300611694      NaN
283098  4493300611695      NaN
283099  4493300611696      NaN
283100  4493300611697      NaN
283101  4493300611698      NaN

[283102 rows x 2 columns]

In [49]:
tg_data_df["Tg_rounded"] = tg_data_df["Tg"].round(-1)
tg_data_df

                   ID       Tg  Tg_rounded
0         20400020000      NaN         NaN
1         20500020001  1017.15      1020.0
2         20500020002  1096.15      1100.0
3         20500020003  1013.15      1010.0
4         20500020004  1013.15      1010.0
...               ...      ...         ...
283097  4493300611694      NaN         NaN
283098  4493300611695      NaN         NaN
283099  4493300611696      NaN         NaN
283100  4493300611697      NaN         NaN
283101  4493300611698      NaN         NaN

[283102 rows x 3 columns]

In [75]:
tg_data_df[(tg_data_df["Tg"] > 278) & (tg_data_df["Tg"] < 281)]

                   ID      Tg  Tg_rounded
71571   1035700042905  279.95       280.0
71577   1035700042911  278.25       280.0
138398  2520300350673  280.15       280.0
141528  2562100352142  280.15       280.0
143704  2589800306191  278.15       280.0
144445  2595000306683  280.15       280.0
147642  2628700354458  280.15       280.0
219713  3612900432948  280.15       280.0

In [ ]:
1035700042905
1035700042911
2589800306191

In [76]:
df = compounds_data[compounds_data["ID"] == 1035700042905]
df

,ID,SiO2,P2O5,ZrO2,Na2O,Al2O3,Fe2O3,CaO,MgO,K2O,...,UF2,Ba(H2PO4)2,AlPO4,AgGaS2,AgAsS2,MgS,Na2B4O7,CaCO3,AsTe3,Re2O7
71571,1035700042905,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [77]:
non_zero_columns = df.loc[df['ID'] == 2401500179282].loc[:, (df != 0).any(axis=0)].columns
non_zero_columns

Index(['ID', 'CsCl', 'AgI', 'AgCl'], dtype='object')

In [79]:
df[non_zero_columns].to_clipboard()

In [82]:
print(get_smiles("CsCl"))
print(get_smiles("AgI"))
print(get_smiles("AgCl"))

[Cl-].[Cs+]
None
Cl[Ag]

In [ ]:
[Cs+].[Cl-].[Ag+].[I-].[Ag+].[Cl-]

In [57]:
compounds_data.iloc[2401500179282, :]

IndexError: single positional indexer is out-of-bounds

In [20]:
compounds_data = data[[col for col in data.columns if "compounds" in col]]
compounds_data

              compounds                                                \
                   SiO2      P2O5      ZrO2      Na2O     Al2O3 Fe2O3
ID
20400020000    1.000000  0.000000  0.000000  0.000000  0.000000   0.0
20500020001    0.453500  0.113500  0.093100  0.339900  0.000000   0.0
20500020002    0.399860  0.113189  0.152985  0.333967  0.000000   0.0
20500020003    0.486449  0.089709  0.109511  0.314331  0.000000   0.0
20500020004    0.482400  0.085700  0.125900  0.306000  0.000000   0.0
...                 ...       ...       ...       ...       ...   ...
4493300611694  0.620100  0.000000  0.000000  0.000000  0.113900   0.0
4493300611695  0.729376  0.000000  0.000560  0.000000  0.113481   0.0
4493300611696  0.717807  0.000000  0.000570  0.000000  0.108001   0.0
4493300611697  0.668267  0.000000  0.000000  0.061197  0.201590   0.0
4493300611698  0.682732  0.000000  0.000000  0.000000  0.130687   0.0

                                                 ...                        \
                    CaO       MgO      K2O  MnO  ...  UF2 Ba(H2PO4)2 AlPO4
ID                                               ...
20400020000    0.000000  0.000000  0.00000  0.0  ...  0.0        0.0   0.0
20500020001    0.000000  0.000000  0.00000  0.0  ...  0.0        0.0   0.0
20500020002    0.000000  0.000000  0.00000  0.0  ...  0.0        0.0   0.0
20500020003    0.000000  0.000000  0.00000  0.0  ...  0.0        0.0   0.0
20500020004    0.000000  0.000000  0.00000  0.0  ...  0.0        0.0   0.0
...                 ...       ...      ...  ...  ...  ...        ...   ...
4493300611694  0.079400  0.150700  0.00000  0.0  ...  0.0        0.0   0.0
4493300611695  0.072088  0.030595  0.00000  0.0  ...  0.0        0.0   0.0
4493300611696  0.108101  0.000000  0.00000  0.0  ...  0.0        0.0   0.0
4493300611697  0.035698  0.000000  0.00073  0.0  ...  0.0        0.0   0.0
4493300611698  0.115288  0.001600  0.00000  0.0  ...  0.0        0.0   0.0


              AgGaS2 AgAsS2  MgS Na2B4O7 CaCO3 AsTe3 Re2O7
ID
20400020000      0.0    0.0  0.0     0.0   0.0   0.0   0.0
20500020001      0.0    0.0  0.0     0.0   0.0   0.0   0.0
20500020002      0.0    0.0  0.0     0.0   0.0   0.0   0.0
20500020003      0.0    0.0  0.0     0.0   0.0   0.0   0.0
20500020004      0.0    0.0  0.0     0.0   0.0   0.0   0.0
...              ...    ...  ...     ...   ...   ...   ...
4493300611694    0.0    0.0  0.0     0.0   0.0   0.0   0.0
4493300611695    0.0    0.0  0.0     0.0   0.0   0.0   0.0
4493300611696    0.0    0.0  0.0     0.0   0.0   0.0   0.0
4493300611697    0.0    0.0  0.0     0.0   0.0   0.0   0.0
4493300611698    0.0    0.0  0.0     0.0   0.0   0.0   0.0

[283102 rows x 625 columns]

In [ ]:
compounds_data.columns = compounds_data.columns.get_level_values(1)

,SiO2,P2O5,ZrO2,Na2O,Al2O3,Fe2O3,CaO,MgO,K2O,MnO,...,UF2,Ba(H2PO4)2,AlPO4,AgGaS2,AgAsS2,MgS,Na2B4O7,CaCO3,AsTe3,Re2O7
ID,,,,,,,,,,,,,,,,,,,,,
20400020000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20500020001,0.453500,0.113500,0.093100,0.339900,0.000000,0.0,0.000000,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20500020002,0.399860,0.113189,0.152985,0.333967,0.000000,0.0,0.000000,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20500020003,0.486449,0.089709,0.109511,0.314331,0.000000,0.0,0.000000,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20500020004,0.482400,0.085700,0.125900,0.306000,0.000000,0.0,0.000000,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4493300611694,0.620100,0.000000,0.000000,0.000000,0.113900,0.0,0.079400,0.150700,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4493300611695,0.729376,0.000000,0.000560,0.000000,0.113481,0.0,0.072088,0.030595,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4493300611696,0.717807,0.000000,0.000570,0.000000,0.108001,0.0,0.108101,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4493300611697,0.668267,0.000000,0.000000,0.061197,0.201590,0.0,0.035698,0.000000,0.00073,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4493300611698,0.682732,0.000000,0.000000,0.000000,0.130687,0.0,0.115288,0.001600,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [61]:
compounds_data = compounds_data.reset_index()
compounds_data

,ID,SiO2,P2O5,ZrO2,Na2O,Al2O3,Fe2O3,CaO,MgO,K2O,...,UF2,Ba(H2PO4)2,AlPO4,AgGaS2,AgAsS2,MgS,Na2B4O7,CaCO3,AsTe3,Re2O7
0,20400020000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20500020001,0.453500,0.113500,0.093100,0.339900,0.000000,0.0,0.000000,0.000000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,20500020002,0.399860,0.113189,0.152985,0.333967,0.000000,0.0,0.000000,0.000000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20500020003,0.486449,0.089709,0.109511,0.314331,0.000000,0.0,0.000000,0.000000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,20500020004,0.482400,0.085700,0.125900,0.306000,0.000000,0.0,0.000000,0.000000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283097,4493300611694,0.620100,0.000000,0.000000,0.000000,0.113900,0.0,0.079400,0.150700,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
283098,4493300611695,0.729376,0.000000,0.000560,0.000000,0.113481,0.0,0.072088,0.030595,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
283099,4493300611696,0.717807,0.000000,0.000570,0.000000,0.108001,0.0,0.108101,0.000000,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
283100,4493300611697,0.668267,0.000000,0.000000,0.061197,0.201590,0.0,0.035698,0.000000,0.00073,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
283101,4493300611698,0.682732,0.000000,0.000000,0.000000,0.130687,0.0,0.115288,0.001600,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [85]:
element_data = data[[col for col in data.columns if "elements" in col]]
element_data.columns = element_data.columns.get_level_values(1)
element_data = element_data.reset_index()
element_data

,ID,H,Li,Be,B,C,N,O,F,Na,...,W,Re,Pt,Au,Hg,Tl,Pb,Bi,Th,U
0,20400020000,0.0,0.0,0.0,0.000000,0.0,0.0,0.666667,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20500020001,0.0,0.0,0.0,0.000000,0.0,0.0,0.579213,0.0,0.196815,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,20500020002,0.0,0.0,0.0,0.000000,0.0,0.0,0.580869,0.0,0.193449,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20500020003,0.0,0.0,0.0,0.000000,0.0,0.0,0.581986,0.0,0.187167,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,20500020004,0.0,0.0,0.0,0.000000,0.0,0.0,0.583672,0.0,0.183080,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283097,4493300611694,0.0,0.0,0.0,0.000000,0.0,0.0,0.625485,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
283098,4493300611695,0.0,0.0,0.0,0.001948,0.0,0.0,0.637540,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
283099,4493300611696,0.0,0.0,0.0,0.000000,0.0,0.0,0.635921,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
283100,4493300611697,0.0,0.0,0.0,0.014544,0.0,0.0,0.622226,0.0,0.035890,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
283101,4493300611698,0.0,0.0,0.0,0.041532,0.0,0.0,0.634462,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [90]:
df = element_data[element_data["ID"] == 1035700042905]
df

,ID,H,Li,Be,B,C,N,O,F,Na,...,W,Re,Pt,Au,Hg,Tl,Pb,Bi,Th,U
71571,1035700042905,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [91]:
non_zero_columns = df.loc[df['ID'] == 1035700042905].loc[:, (df != 0).any(axis=0)].columns
non_zero_columns

Index(['ID', 'Cl', 'Ag', 'I', 'Cs'], dtype='object')

In [ ]:
1035700042905

In [ ]:
compounds_data.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
import pubchempy as pcp


def get_smiles(chemical_name):
    try:
        comp = pcp.get_compounds(chemical_name, "name")
        if comp:
            return comp[0].isomeric_smiles
        else:
            return None
    except Exception as e:
        print(f"Error retrieving SMILES for {chemical_name}: {e}")
        return None

In [23]:
# Extract the unique compounds from your dataset
compound_names = [col[1] for col in compounds_data.columns]

# Create a dictionary of {oxide: SMILES}
smiles_dict = {name: get_smiles(name) for name in compound_names[:100]}

Error retrieving SMILES for NaCl: 'PUGREST.ServerBusy'
Error retrieving SMILES for SO3: 'PUGREST.ServerBusy'

In [24]:
smiles_dict

{'SiO2': 'O=[Si]=O',
 'P2O5': 'O=P12OP3(=O)OP(=O)(O1)OP(=O)(O2)O3',
 'ZrO2': 'O=[Zr]=O',
 'Na2O': '[O-2].[Na+].[Na+]',
 'Al2O3': None,
 'Fe2O3': None,
 'CaO': None,
 'MgO': None,
 'K2O': None,
 'MnO': 'CC(C)[C@@H](C(=O)N1CCC[C@H]1C(=O)N[C@@H](CC(=O)NS(=O)(=O)C)C(=O)S)NC(=O)C2=CC3=CC=CC=C3C=C2',
 'GeO2': None,
 'Li2O': '[Li+].[Li+].[OH-]',
 'Ta2O5': None,
 'ZnO': None,
 'SrO': None,
 'CdO': None,
 'SnO2': 'O=[Sn]=O',
 'B2O3': 'B(=O)OB=O',
 'La2O3': 'O=[La]O[La]=O',
 'Ga2O3': 'O=[Ga]O[Ga]=O',
 'Y2O3': None,
 'TiO2': 'O=[Ti]=O',
 'Nb2O5': 'O=[Nb](=O)O[Nb](=O)=O',
 'PbO': 'CCCCOCCOCCOCC1=CC2=C(C=C1CCC)OCO2',
 'HfO2': None,
 'WO3': None,
 'Sb2O3': 'O1[Sb]2O[Sb]3O[Sb]1O[Sb](O2)O3',
 'Bi2O3': 'O=[Bi]O[Bi]=O',
 'CdCl2': 'Cl[Cd]Cl',
 'KCl': '[Cl-].[K+]',
 'BaCl2': '[Cl-].[Cl-].[Ba+2]',
 'CsCl': '[Cl-].[Cs+]',
 'TlCl': 'Cl[Tl]',
 'CaCl2': '[Cl-].[Cl-].[Ca+2]',
 'CdI2': '[Cd](I)I',
 'CsI': None,
 'BaI2': 'C1CN(CCN1)CC(CN2C3=C(C=C(C=C3)Br)C4=C2C=CC(=C4)Br)F',
 'PbI2': 'I[Pb]I',
 'CdBr2': 'Br[Cd]Br',
 'KBr': '[K+].[Br-]',
 'CsBr': '[Br-].[Cs+]',
 'BaBr2': '[Br-].[Br-].[Ba+2]',
 'CdF2': 'F[Cd]F',
 'NaCl': None,
 'BaF2': None,
 'PbF2': 'F[Pb]F',
 'PbCl2': 'Cl[Pb]Cl',
 'NaF': '[F-].[Na+]',
 'InF3': 'F[In](F)F',
 'GaF3': None,
 'ZnF2': 'F[Zn]F',
 'LaF3': 'F[La](F)F',
 'YF3': 'CC1=NC=C(C(=N1)N)CNC(C)CS',
 'BaO': None,
 'Cr2O3': 'O=[Cr]O[Cr]=O',
 'AlF3': 'F[Al](F)F',
 'SiF4': 'F[Si](F)(F)F',
 'Cu2O': '[O-2].[Cu+].[Cu+]',
 'CaF2': '[F-].[F-].[Ca+2]',
 'BeO': None,
 'CuO': 'O=[Cu]',
 'Nd2O3': '[O-2].[O-2].[O-2].[Nd+3].[Nd+3]',
 'CeO2': 'O=[Ce]=O',
 'Cs2O': '[OH-].[Cs+].[Cs+]',
 'As2O3': 'O1[As]2O[As]3O[As]1O[As](O2)O3',
 'SO3': None,
 'F': 'FF',
 'NH4NO3': None,
 'MgF2': None,
 'SrF2': '[F-].[F-].[Sr+2]',
 'Rb2O': None,
 'Pd': '[Pd]',
 'Rh': '[Rh]',
 'Ru': '[Ru]',
 'MoO3': 'O=[Mo](=O)=O',
 'FeO': None,
 'PbBr2': 'Br[Pb]Br',
 'Mn2O3': None,
 'KF': None,
 'SO2': 'O=S=O',
 'ThO2': 'O=[Th]=O',
 'Ag2O': '[O-2].[Ag+].[Ag+]',
 'Ag2S': '[SH-].[Ag].[Ag+]',
 'Fe': '[Fe]',
 'Mo': '[Mo]',
 'TeO2': 'O=[Te]=O',
 'Tl2O': None,
 'CoO': 'O=[Co]',
 'In2O3': None,
 'Sc2O3': '[O-2].[O-2].[O-2].[Sc+3].[Sc+3]',
 'ZrF4': 'F[Zr](F)(F)F',
 'ThF4': None,
 'HfF4': None,
 'F2': 'FF',
 'NiO': 'C1=CC(=CN=C1)C(=O)O',
 'ErF3': None,
 'V2O5': 'O=[V](=O)O[V](=O)=O',
 'Li2SO4': '[Li+].[Li+].[O-]S(=O)(=O)[O-]',
 'As2O5': 'O=[As](=O)O[As](=O)=O',
 'Cl': 'ClCl'}

In [29]:
compounds_data_columns = [
    comp for _, comp in compounds_data.columns
]

compounds_data_columns[:5]

['SiO2', 'P2O5', 'ZrO2', 'Na2O', 'Al2O3']

In [30]:
# List of polymer names to check
polymer_names = [
    "Poly(benzyl acrylate)",
    "Poly(4-biphenyl acrylate)",
    "Poly(butyl acrylate)",
    "Poly(sec-butyl acrylate)",
    "Poly(2-tertbutylphenyl acrylate)",
]

# Check if any of these names exist in the dataset
matching_polymers = [name for name in polymer_names if name in compounds_data_columns]

print("Matching Polymers Found in Dataset:", matching_polymers)

Matching Polymers Found in Dataset: []

In [31]:
# Fetch SMILES manually for the given polymers
polymer_smiles = {name: get_smiles(name) for name in polymer_names}

import pandas as pd

# Convert to a dataframe for easy viewing
polymer_smiles_df = pd.DataFrame.from_dict(
    polymer_smiles, orient="index", columns=["SMILES"]
)

polymer_smiles_df

                                 SMILES
Poly(benzyl acrylate)              None
Poly(4-biphenyl acrylate)          None
Poly(butyl acrylate)               None
Poly(sec-butyl acrylate)           None
Poly(2-tertbutylphenyl acrylate)   None

In [33]:
monomer_names = [
    "Benzyl acrylate",
    "4-Biphenyl acrylate",
    "Butyl acrylate",
    "Sec-butyl acrylate",
    "2-Tertbutylphenyl acrylate",
]

# Fetch SMILES for the monomers instead of full polymer names
monomer_smiles = {name: get_smiles(name) for name in monomer_names}


# Convert to a dataframe for easy viewing
monomer_smiles_df = pd.DataFrame.from_dict(
    monomer_smiles, orient="index", columns=["SMILES"]
)
monomer_smiles_df

                                           SMILES
Benzyl acrylate             C=CC(=O)OCC1=CC=CC=C1
4-Biphenyl acrylate                          None
Butyl acrylate                      CCCCOC(=O)C=C
Sec-butyl acrylate                CCC(C)OC(=O)C=C
2-Tertbutylphenyl acrylate                   None

In [34]:
import pubchempy as pcp


def get_smiles(chemical_name):
    """Fetch SMILES using PubChem, handling errors properly."""
    try:
        comp = pcp.get_compounds(chemical_name, "name")
        return comp[0].isomeric_smiles if comp else None
    except Exception:
        return None


# Convert polymer names into possible monomer equivalents
monomer_names = {
    "Poly(benzyl acrylate)": "Benzyl acrylate",
    "Poly(4-biphenyl acrylate)": "4-Biphenyl acrylate",
    "Poly(butyl acrylate)": "Butyl acrylate",
    "Poly(sec-butyl acrylate)": "Sec-butyl acrylate",
    "Poly(2-tertbutylphenyl acrylate)": "2-Tertbutylphenyl acrylate",
}

# Try to fetch SMILES for monomers instead of full polymer names
monomer_smiles = {poly: get_smiles(mono) for poly, mono in monomer_names.items()}

# Convert to a DataFrame for easy handling
import pandas as pd

df_smiles = pd.DataFrame.from_dict(monomer_smiles, orient="index", columns=["SMILES"])
print(df_smiles)

                                                 SMILES
Poly(benzyl acrylate)             C=CC(=O)OCC1=CC=CC=C1
Poly(4-biphenyl acrylate)                          None
Poly(butyl acrylate)                      CCCCOC(=O)C=C
Poly(sec-butyl acrylate)                CCC(C)OC(=O)C=C
Poly(2-tertbutylphenyl acrylate)                   None

In [71]:
comp = pcp.Compound.from_cid(2401500179282)  # Replace CID with the actual number
print(comp.isomeric_smiles)

BadRequestError: 'PUGREST.BadRequest'

In [2]:
import msaccessdb
import pandas as pd

In [6]:
import pandas as pd
import sqlalchemy as sa

# Update with your .mdb file path
db_path = r"./data/SciGlass/select/select.mdb"

# Connection string
connection_string = f"access+pyodbc://@/{db_path}?driver=Microsoft Access Driver (*.mdb)"

# Create the engine
engine = sa.create_engine(connection_string)

# Read the table into a pandas DataFrame
table_name = 'YourTableName'  # Replace with your actual table name
df = pd.read_sql(f'SELECT * FROM {table_name}', engine)

# Take a peek at the data
print(df.head())

InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)

In [ ]:
import sqlalchemy as sa

engine = create_engine(connection_string)
table_names = engine.table_names()
print(table_name)

NameError: name 'create_engine' is not defined

In [3]:
db_path = r"./data/SciGlass/select/select.mdb"

conn_str = r"DRIVER={Microsoft Access Driver (*.mdb)};" r"DBQ=" + db_path + ";"

conn = pyodbc.connect(conn_str)

query = "SELECT * FROM ARHIV"


df = pd.read_sql(query, conn)

conn.close()

NameError: name 'pyodbc' is not defined

In [5]:
import accessdb
import pandas as pd

# Load the Access database
db = accessdb.open(r"./data/SciGlass/select/select.mdb")

# List all tables
print(db.tables)

# Load 'ARHIV' table into a Pandas DataFrame
df = db.to_pandas("ARHIV")
print(df.head())

AttributeError: module 'accessdb' has no attribute 'open'